# Generated by Django 4.0.6 on 2022-07-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0002_alter_profilemodel_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImg',
            field=models.ImageField(blank=True, default='', upload_to='posts'),
        ),
    ]
