# Generated by Django 4.0.6 on 2022-07-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0003_remove_post_post_post_postimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(upload_to='ProfilePics'),
        ),
    ]
