# Generated by Django 4.0.6 on 2022-07-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0004_alter_profilemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImg',
            field=models.ImageField(blank=True, upload_to='media/posts'),
        ),
    ]
