# Generated by Django 4.0.6 on 2022-07-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0007_alter_post_postimg_alter_profilemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(upload_to='ProfilePics'),
        ),
    ]
